[project]
name = "ODAT-SE"
dynamic = ["version"]
description = "Open Data Analysis Tool for Science and Engineering"
authors = [{ name = "2DMAT developers", email = "2dmat-dev@issp.u-tokyo.ac.jp" }]
requires-python = ">=3.9"
readme = "README.md"
license = "MPL-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "numpy>=1.14",
    "tomli>=1.2 ; python_full_version < '3.11'",
    "matplotlib>= 3",
]

[project.optional-dependencies]
min_search = ["scipy>=1,<2"]
bayes = ["physbo>= 2.0.0"]
exchange = ["mpi4py>= 3.1.0"]
progress = ["tqdm>= 4"]
all = [
    "scipy>=1,<2",
    "mpi4py>= 3.1.0",
    "physbo>= 2.0.0",
    "tqdm>= 4",
]

[project.urls]
Repository = "https://github.com/issp-center-dev/ODAT-SE"

[project.scripts]
odatse = "odatse:cli"
odatse_neighborlist = "odatse.util.neighborlist:main"
odatse_extract_combined = "odatse.scripts.extract_combined:main"
odatse_plt_1D_histogram = "odatse.scripts.plt_1D_histogram:main"
odatse_plt_2D_histogram = "odatse.scripts.plt_2D_histogram:main"
odatse_plt_model_evidence = "odatse.scripts.plt_model_evidence:main"
odatse_separateT = "odatse.scripts.separateT:main"
odatse_summarize_each_T = "odatse.scripts.summarize_each_T:main"

[tool.hatch.version]
path = "src/odatse/_version.py"

[tool.hatch.build.targets.sdist]
include = ["src/odatse"]

[tool.hatch.build.targets.wheel]
include = ["src/odatse"]

[tool.hatch.build.targets.wheel.sources]
"src/odatse" = "odatse"

[build-system]
requires = ["hatchling >= 1.27.0, < 2.0.0"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "sphinx>=7.4.7",
    "pydata-sphinx-theme>=0.16.1",
    "sphinxcontrib-mermaid>=1.2.3",
]
