[base]
dimension = 1
output_dir = "output_par_test"

[solver]
name = "custom"

[runner]
[runner.log]
interval = 20

[algorithm]
name = "mapper"

[algorithm.param]
max_list = [20]
min_list = [1]
num_list = [20]
