[base]
dimension = 10
output_dir = "output"

[solver]
name = "analytical"
function_name = "rastrigin"

[algorithm]
name = "ttopt"
seed = 12345

[algorithm.param]
max_list = [5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12, 5.12]
min_list = [-5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12, -5.12]

[algorithm.ttopt]
p_points = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
q_points = [25, 25, 25, 25, 25, 25, 25, 25, 25, 25]
r_max = 4
max_f_eval = 100000
