name: test for building doc

on: [push]

jobs:
  check-build-doc:
    runs-on: ubuntu-22.04
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Prepare LaTeX env
      run: |
        sudo apt update
        sudo apt install openmpi-bin libopenmpi-dev
        sudo apt install \
          texlive-latex-recommended texlive-latex-extra texlive-xetex \
          texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra latexmk
        kanji-config-updmap-sys ipaex

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme
        cd ${GITHUB_WORKSPACE}/main
        python -m pip install '.[all]'

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/main/doc
        sh ./make.sh
