name: test for building doc

on: [push]

jobs:
  check-build-doc:
    runs-on: ubuntu-22.04
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4.x

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Prepare LaTeX env
      run: |
        sudo apt update
        sudo apt install \
          texlive-latex-recommended texlive-latex-extra texlive-xetex \
          texlive-lang-japanese texlive-fonts-recommended texlive-fonts-extra latexmk
        kanji-config-updmap-sys ipaex

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install sphinx

    - name: Build
      run: |
        for lang in ja en; do
          cd ${GITHUB_WORKSPACE}/main/doc/${lang}
          make html
          make latexpdf
        done
