name: upload package to PyPI

on:
  push:
    # tags: ['*']
    tags: ['disabled-because-odatse-is-not-yet-ready-in-pypi']

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install python packages
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Publish
      run: |
          cd ${GITHUB_WORKSPACE}
          poetry publish --build -u __token__ -p "${{ secrets.PYPI_DEPLOY_TOKEN }}"
